// AUTO-GENERATED by scripts/build-projects.mjs — DO NOT EDIT BY HAND.
// Source: templates/Projects/PROJECTS.csv (+ optional media sidecars).
// Regenerate with: npm run build:projects (runs automatically before dev/build).

import type { Project } from './projects';

export const csvProjects: Project[] = [];
